* Capra 30x30 sync tool

*Disclaimer:* I'm not affiliated with Capra. This is a hacky tool for lazy runners, use at your own risk.

This tool lets you copy runs from strava to the Capra 30x30 page. It runs totally on your browser, nothing is sent other than the runs you upload.

** Installation

Copy the following to a bookmark.

#+begin_src shell :results code :exports results
echo "javascript:$(npx uglifyjs magic.js)"
#+end_src

#+RESULTS:
#+begin_src shell
javascript:(()=>{switch(location.host){case"www.strava.com":globalThis.selectedData={};globalThis.copyData=elt=>{let row=elt.parentElement.parentElement.parentElement;let[s,m,h]=row.querySelector(".col-time").textContent.split(":").reverse();let time=(h||0)*60+1*m;let dist=row.querySelector(".col-dist").textContent.trim().split("
")[0];let date=new Date(row.querySelector(".col-date").textContent.split(" ")[1].split("/")).toISOString().split("T")[0];if(date){let existing=globalThis.selectedData[date];globalThis.selectedData[date]={time:(existing?.time||0)+time,dist:(existing?.dist||0)+1*dist}}};globalThis.openCapraUrl=()=>{let selected=document.querySelectorAll(".do-sync:checked");if(selected.length==0){alert("No activities selected to upload");return}globalThis.selectedData={};selected.forEach(copyData);const url="https://30x30.capra.run/#"+btoa(JSON.stringify(globalThis.selectedData));window.open(url)};document.querySelector(".page.container").innerHTML+='<button style="position:fixed;top:5em;right:5em;" onclick="openCapraUrl()">Upload to Capra</button>';document.querySelectorAll("tbody .col-actions").forEach(x=>x.innerHTML+='<label>sync to 30x30<input type="checkbox" class="do-sync"/></label>');break;case"30x30.capra.run":globalThis.upload=()=>{const uploadData=JSON.parse(atob(window.location.hash.substr(1)));let i=1;let promises=[];for(let[date,{time,dist}]of Object.entries(uploadData)){promises.push(new Promise(function(resolve,reject){setTimeout(()=>fetch("https://30x30.capra.run/api/exercise",{headers:{accept:"application/json, text/plain, */*","content-type":"application/json"},body:`{\"minutes\":${time},\"km\":${dist||0},\"date\":\"${date}\"}`,method:"POST",mode:"cors",credentials:"include"}).then(res=>{if(res.ok){resolve(date)}else{alert(`There was a problem with ${date}`)}}),i*350)}));i++;Promise.all(promises).then(res=>{alert("updated the following dates: "+res.join())})}};if(!location.hash){alert("No data to upload. Return to strava and click link to open a new window.");return}else{document.querySelector(".MuiBox-root:first-child .MuiContainer-root").innerHTML+='<button style="position:fixed;top:5em;left:1em;" onclick="upload()">Upload to Capra</button>'}break;default:alert("only works when either on capra or strava websites")}})();
#+end_src

Double-check: You might need to manually type =javascript:= at the start of the link.

** How to Upload from Strava

Do this each time you want to upload new runs or correct existing data.

A couple of notes before you start
- multiple Strava activities on the same day are added together
- *Strava activities overwrite Capra activities for the same day*
- it works for any activity type, as long as the distance and time are visible on the strava activities view
- all other Capra times are not changed

Steps:
1. log in to the Capra site using your email link
2. visit https://www.strava.com/athlete/training
3. click the bookmark once the activities have loaded, you should see a button appear and checkboxes on each activity
4. check all the activities you want to upload
5. click the 'upload to capra' button
6. a new page with the Capra 30x30 activities should open (you should still see a 'sign out' button)
7. on the Capra page click the bookmark again, you should see another button appear
8. you should eventually see a popup saying which dates were updated
9. *close the capra window*

** How it Works

The bookmark contains Javascript that copies the selected activities from the Strava page, adds it to the Capra URL in the new page that is opened.
The second time you click the bookmark it takes the data from the URL and sends it to Capra using your access credentials.
